config/routes.rb
Rails.application.routes.draw do
  resources :riders
  resources :drivers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'riders#index'

  # get 'welcome/home', to: 'welcome#home'
  # get 'welcome/about', to: 'welcome#about'
  root 'welcome#home'
  get 'about', to: 'welcome#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
end

app/models/rider.rb
class Rider < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:name, :description)
    end
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  before_action :set_rider, only: [:show, :edit, :update, :destroy]

  # GET /riders
  # GET /riders.json
  def index
    @riders = Rider.all
  end

  # GET /riders/1
  # GET /riders/1.json
  def show
  end

  # GET /riders/new
  def new
    @rider = Rider.new
  end

  # GET /riders/1/edit
  def edit
  end

  # POST /riders
  # POST /riders.json
  def create
    @rider = Rider.new(rider_params)

    respond_to do |format|
      if @rider.save
        format.html { redirect_to @rider, notice: 'Rider was successfully created.' }
        format.json { render :show, status: :created, location: @rider }
      else
        format.html { render :new }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /riders/1
  # PATCH/PUT /riders/1.json
  def update
    respond_to do |format|
      if @rider.update(rider_params)
        format.html { redirect_to @rider, notice: 'Rider was successfully updated.' }
        format.json { render :show, status: :ok, location: @rider }
      else
        format.html { render :edit }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /riders/1
  # DELETE /riders/1.json
  def destroy
    @rider.destroy
    respond_to do |format|
      format.html { redirect_to riders_url, notice: 'Rider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rider
      @rider = Rider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rider_params
      params.require(:rider).permit(:name, :home, :work)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/riders_helper.rb
module RidersHelper
end

app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :driver_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :driver_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.name %></td>
        <td><%= driver.description %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>
<br />
<%= link_to 'home', root_path %>
<br />
<%= link_to 'about', about_path %>
<br />
<%= link_to 'riders', riders_path %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @driver.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @driver.description %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RideSharing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/riders/_form.html.erb
<%= form_with(model: rider, local: true) do |form| %>
  <% if rider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rider.errors.count, "error") %> prohibited this rider from being saved:</h2>

      <ul>
      <% rider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :rider_name %>
  </div

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :rider_description %>
  </div>

  <div class="field">
    <%= form.label :home %>
    <%= form.text_area :home, id: :rider_home %>
  </div>

  <div class="field">
    <%= form.label :work %>
    <%= form.text_area :work, id: :rider_work %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/riders/edit.html.erb
<h1>Editing Rider</h1>

<%= render 'form', rider: @rider %>

<%= link_to 'Show', @rider %> |
<%= link_to 'Back', riders_path %>

app/views/riders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Riders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Home</th>
      <th>Work</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @riders.each do |rider| %>
      <tr>
        <td><%= rider.name %></td>
        <td><%= rider.description %></td>
        <td><%= rider.home %></td>
        <td><%= rider.work %></td>
        <td><%= link_to 'Show', rider %></td>
        <td><%= link_to 'Edit', edit_rider_path(rider) %></td>
        <td><%= link_to 'Destroy', rider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rider', new_rider_path %>
<br />
<%= link_to 'home', root_path %>
<br />
<%= link_to 'about', about_path %>
<br />
<%= link_to 'drivers', drivers_path %>

app/views/riders/new.html.erb
<h1>New Rider</h1>

<%= render 'form', rider: @rider %>

<%= link_to 'Back', riders_path %>

app/views/riders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rider.name %>
</p>

<p>
  <strong>Home:</strong>
  <%= @rider.home %>
</p>

<p>
  <strong>Work:</strong>
  <%= @rider.work %>
</p>

<%= link_to 'Edit', edit_rider_path(@rider) %> |
<%= link_to 'Back', riders_path %>

app/views/welcome/about.erb
<h1>About</h1>

<%= link_to 'home', root_path %>
<br />
<%= link_to 'riders', riders_path %>
<br />
<%= link_to 'drivers', drivers_path %>

app/views/welcome/home.erb
<h1>Home page!</h1>

<%= link_to 'about', about_path %>
<br />
<%= link_to 'riders', riders_path %>
<br />
<%= link_to 'drivers', drivers_path %>